// src/components/layout/modern-header.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { Clock, Wifi } from 'lucide-react';
import { Badge } from '../ui/badge';
import { formatRelativeTime } from '../../lib/utils';

interface ModernHeaderProps {
  lastUpdate?: Date;
}

export const ModernHeader: React.FC<ModernHeaderProps> = ({ lastUpdate }) => {
  const [currentTime, setCurrentTime] = React.useState(new Date());

  React.useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  return (
    <motion.header
      className="bg-white border-b-4 border-yellow-400 shadow-lg sticky top-0 z-40"
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      transition={{ type: "spring", stiffness: 100, damping: 20 }}
    >
      <div className="max-w-[1850px] mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          {/* Logo y Título */}
          <motion.div
            className="flex items-center gap-4"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
          >
            {/* Logo Oficial Caminos de las Sierras */}
            <motion.div
              className="h-16 w-auto flex items-center justify-center"
              whileHover={{ scale: 1.05 }}
              transition={{ type: "spring", stiffness: 300 }}
            >
              <img
                src="/logo_cs.png"
                alt="Caminos de las Sierras"
                className="h-full w-auto object-contain"
              />
            </motion.div>

            <div className="border-l-2 border-yellow-400 pl-4">
              <h1 className="text-2xl font-black text-primary-700 mb-0.5 tracking-tight">
                Panel de Control Inteligente
              </h1>
              <p className="text-sm text-gray-600 font-medium flex items-center gap-2">
                <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                Monitoreo de Tráfico en Tiempo Real
              </p>
            </div>
          </motion.div>

          {/* Información de Estado */}
          <motion.div
            className="flex items-center gap-4"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
          >
            {/* Hora Actual */}
            <div className="hidden md:flex items-center gap-3 bg-gray-50 rounded-lg px-4 py-2.5 border border-gray-200">
              <Clock className="w-5 h-5 text-primary-600" />
              <div>
                <div className="text-xs text-gray-500 font-semibold">Hora Actual</div>
                <div className="text-base font-bold text-gray-900 tabular-nums">
                  {currentTime.toLocaleTimeString('es-AR', {
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit'
                  })}
                </div>
              </div>
            </div>

            {/* Última Actualización */}
            {lastUpdate && (
              <div className="flex items-center gap-3 bg-gray-50 rounded-lg px-4 py-2.5 border border-gray-200">
                <Wifi className="w-5 h-5 text-green-600" />
                <div>
                  <div className="text-xs text-gray-500 font-semibold">Última Actualización</div>
                  <div className="text-sm font-bold text-gray-900">
                    {formatRelativeTime(lastUpdate)}
                  </div>
                </div>
              </div>
            )}

            {/* Badge de Estado */}
            <motion.div
              animate={{
                scale: [1, 1.05, 1],
              }}
              transition={{ duration: 2, repeat: Infinity }}
            >
              <Badge variant="success" size="lg" className="shadow-md">
                <span className="w-2 h-2 bg-green-500 rounded-full mr-2 animate-pulse"></span>
                EN VIVO
              </Badge>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </motion.header>
  );
};

// apps/frontend-angular/src/app/shared/components/modern-header/modern-header.component.ts
import { Component, inject, signal, OnInit, OnDestroy, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgIcon } from '@ng-icons/core';
import { WebSocketService, TTSService, ApiService } from '../../../core/services';
import { NotificationStore } from '../../../core/stores';

@Component({
  selector: 'app-modern-header',
  standalone: true,
  imports: [CommonModule, NgIcon],
  template: `
    <header class="sticky top-0 z-40 bg-veltrix-card border-b-4 border-yellow-400 shadow-lg">
      <div class="flex items-center justify-between px-6 py-3">
        <!-- Left: Logo & Title -->
        <div class="flex items-center gap-4">
          <!-- Logo -->
          <div class="relative w-16 h-12 bg-gradient-to-br from-green-400 to-yellow-400 rounded-lg flex items-center justify-center shadow-lg overflow-hidden">
            <svg viewBox="0 0 100 60" class="w-full h-full p-1">
              <path d="M10 50 L30 20 L50 35 L70 15 L90 40" fill="none" stroke="currentColor" stroke-width="6" class="text-veltrix-bg" />
              <circle cx="30" cy="20" r="4" class="fill-veltrix-bg" />
              <circle cx="50" cy="35" r="4" class="fill-veltrix-bg" />
              <circle cx="70" cy="15" r="4" class="fill-veltrix-bg" />
            </svg>
          </div>
          
          <!-- Title -->
          <div>
            <h1 class="text-xl font-bold text-veltrix-text flex items-center gap-2">
              Panel Ejecutivo
            </h1>
            <p class="text-xs text-veltrix-muted flex items-center gap-1">
              <span class="w-2 h-2 rounded-full bg-veltrix-success animate-pulse"></span>
              Monitoreo de Tráfico en Tiempo Real
            </p>
          </div>
        </div>

        <!-- Center: Quick Actions -->
        <div class="hidden md:flex items-center gap-4">
          <button class="p-2 rounded-lg bg-veltrix-bg hover:bg-veltrix-border transition-colors" title="Modo oscuro">
            <ng-icon name="lucideMoon" class="text-veltrix-muted" size="18" />
          </button>
          <button class="p-2 rounded-lg bg-veltrix-bg hover:bg-veltrix-border transition-colors" title="Notificaciones">
            <ng-icon name="lucideBell" class="text-veltrix-muted" size="18" />
          </button>
        </div>

        <!-- Right: Status & Time -->
        <div class="flex items-center gap-4">
          <!-- Time -->
          <div class="hidden lg:flex items-center gap-3 px-4 py-2 bg-veltrix-bg rounded-xl">
            <ng-icon name="lucideClock" class="text-veltrix-muted" size="18" />
            <div class="text-right">
              <div class="text-sm font-bold text-veltrix-text">HORA ACTUAL</div>
              <div class="text-lg font-mono font-bold text-veltrix-text">{{ currentTime() }}</div>
            </div>
          </div>

          <!-- Last Update -->
          <div class="hidden lg:flex items-center gap-3 px-4 py-2 bg-veltrix-bg rounded-xl">
            <ng-icon name="lucideRefreshCw" class="text-veltrix-success" size="18" />
            <div class="text-right">
              <div class="text-sm font-bold text-veltrix-text">ÚLTIMA ACTUALIZACIÓN</div>
              <div class="text-sm text-veltrix-success font-medium">Ahora mismo</div>
            </div>
          </div>

          <!-- Refresh Button -->
          <button 
            (click)="onRefresh()"
            class="flex items-center gap-2 px-4 py-2 bg-veltrix-primary text-white rounded-xl hover:brightness-110 transition-all"
          >
            <ng-icon name="lucideRefreshCw" size="16" [class.animate-spin]="isRefreshing()" />
            <span class="font-medium">Actualizar</span>
          </button>

          <!-- Live Badge -->
          <div class="px-4 py-2 bg-veltrix-success text-white rounded-xl font-bold text-sm flex items-center gap-2">
            <span class="w-2 h-2 rounded-full bg-white animate-pulse"></span>
            EN VIVO
          </div>
        </div>
      </div>
    </header>
  `,
})
export class ModernHeaderComponent implements OnInit, OnDestroy {
  @Output() refresh = new EventEmitter<void>();
  
  private wsService = inject(WebSocketService);
  private apiService = inject(ApiService);
  readonly notificationStore = inject(NotificationStore);

  readonly wsConnected = this.wsService.connected;
  readonly currentTime = signal('--:--:--');
  readonly isRefreshing = signal(false);

  private clockInterval?: ReturnType<typeof setInterval>;

  ngOnInit(): void {
    this.updateClock();
    this.clockInterval = setInterval(() => this.updateClock(), 1000);
  }

  ngOnDestroy(): void {
    if (this.clockInterval) {
      clearInterval(this.clockInterval);
    }
  }

  private updateClock(): void {
    const now = new Date();
    this.currentTime.set(
      now.toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
    );
  }

  onRefresh(): void {
    this.isRefreshing.set(true);
    this.apiService.refreshAll();
    this.refresh.emit();
    setTimeout(() => this.isRefreshing.set(false), 1000);
  }
}
